const WEATHER_DATA_FETCH_REQUESTED = "WEATHER_DATA_REQUESTED";
const WEATHER_DATA_FETCH_FAILED = "WEATHER_DATA_FETCH_FAILED";
const WEATHER_DATA_FETCH_SUCCEEDED = "WEATHER_DATA_FETCH_SUCCEEDED";

const SENSEBOXES_FETCH_REQUESTED = "SENSEBOXES_FETCH_REQUESTED";
const SENSEBOXES_FETCH_FAILED = "SENSEBOXES_FETCH_FAILED";
const SENSEBOXES_FETCH_SUCCEEDED = "SENSEBOXES_FETCH_SUCCEEDED";

const SENSEBOX_INFO_FETCH_REQUESTED = "SENSEBOX_INFO_FETCH_REQUESTED";
const SENSEBOX_INFO_FETCH_FAILED = "SENSEBOX_INFO_FETCH_FAILED";
const SENSEBOX_INFO_FETCH_SUCCEEDED = "SENSEBOX_INFO_FETCH_SUCCEEDED";

export {
  WEATHER_DATA_FETCH_REQUESTED,
  WEATHER_DATA_FETCH_FAILED,
  WEATHER_DATA_FETCH_SUCCEEDED,

  SENSEBOXES_FETCH_REQUESTED,
  SENSEBOXES_FETCH_FAILED,
  SENSEBOXES_FETCH_SUCCEEDED,

  SENSEBOX_INFO_FETCH_REQUESTED,
  SENSEBOX_INFO_FETCH_FAILED,
  SENSEBOX_INFO_FETCH_SUCCEEDED,
};
