const CONSTANTS = {
    SENSEBOX_INACTIVITY_TIME_DAYS: 3,
    SENSEBOX_SENSOR_INACTIVITY_TIME_HOURS: 25,
    MAX_BOOKMARKED_BOXES: 5,
    MIN_SENSEBOX_SEARCH_CHARACTERS: 3,
};

export default CONSTANTS;